Develop mayerhofen
Project-Mayerhofen/ha-sap-terraform-deployments pull request #3
Opened 2022-03-25 18:25 UTC by movinalot

Update deprecated Azure LB attribute
Update FortiGate cfg with more granular FW policies
Update Azure Availability Set Naming to match SUSE style

2022-03-28 11:32 UTC, yeoldegrove requested changes
Please remove the 2 old comments.
Otherwise :+1:

2022-03-28 11:32 UTC, yeoldegrove commented on azure/modules/fortinet/fortiadc/main.tf
> +  #resource_group_name = each.value.resource_group_name
please remove

2022-03-28 11:32 UTC, yeoldegrove commented on azure/modules/fortinet/fortigate/main.tf
> +  #resource_group_name = each.value.resource_group_name
please remove

2022-03-28 12:36 UTC, movinalot commented on azure/modules/fortinet/fortiadc/main.tf
> +  #resource_group_name = each.value.resource_group_name
removed

2022-03-28 12:36 UTC, movinalot commented on azure/modules/fortinet/fortigate/main.tf
> +  #resource_group_name = each.value.resource_group_name
removed

2022-03-29 07:52 UTC, yeoldegrove approved these changes

2022-04-14 11:27 UTC, merged